spring.application.name=GestaoEstoque

# Configuração do PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/db_gerenciamento_estoque_inteligente
spring.datasource.username=postgres
spring.datasource.password=0000

# Configuração do Hibernate/JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8089

# CONFIGURAÇÃO DO REDIS (O que faltava!)
spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
# Tempo de vida do cache (ex: 10 minutos)
spring.cache.redis.time-to-live=600000